apiVersion: v1
kind: Secret
metadata:
  name: registry-auth
  namespace: registry
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JEg3WkVqNk8wSWFGSkFJSWdkc1lwVk94dm1wSEg0TWQyTUgyUjJMTE1XRUYxaDc1NnJrUURLCgo=
