apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis
    spec:
      terminationGracePeriodSeconds: 30

      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
              name: redis

          args:
            - "--appendonly"
            - "yes"

          volumeMounts:
            - name: redis-data
              mountPath: /data

          readinessProbe:
            exec:
              command: ["sh","-c","redis-cli ping | grep PONG"]
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            exec:
              command: ["sh","-c","redis-cli ping | grep PONG"]
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

