apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: facial-berkeley-insured-topic.trycloudflare.com/frontend:dev-b132d4d

