apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: dependence-ship-icq-secretariat.trycloudflare.com/frontend:prod-c919777

