apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: transaction
          image: cbs-smile-margaret-suppliers.trycloudflare.com/transaction:dev-f3dea94
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi

  
