apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJmYWNpYWwtYmVya2VsZXktaW5zdXJlZC10b3BpYy50cnljbG91ZGZsYXJlLmNvbSI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJzdHJvbmdwYXNzd29yZCIsImF1dGgiOiJZV1J0YVc0NmMzUnliMjVuY0dGemMzZHZjbVE9In19fQ==

