apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2 
  template:
    spec:
      containers:
        - name: frontend
          image:  cbs-smile-margaret-suppliers.trycloudflare.com/frontend:dev-71448c2

