apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2 
  template:
    spec:
      containers:
        - name: frontend
          image:  episodes-wax-award-apparel.trycloudflare.com/frontend:dev-b132d4d

