apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 999

      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres

          envFrom:
            - secretRef:
                name: postgres-secret

          args:
            - "-c"
            - "max_connections=200"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6

          livenessProbe:
            exec:
              command: ["sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "1Gi"

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

