apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      label: dev
  template:
    metadata:
      labels:
        app: postgres
        label: dev
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 999
        runAsNonRoot: true

        
        
      containers:
        - name: postgres
          image: postgres:15

          # Security context
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # Allow writes for development

          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP

          envFrom:
            - secretRef:
                name: postgres-secret

          args:
            - "-c"
            - "max_connections=200"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf 
              subPath: postgresql.conf
              readOnly: true
 
          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 6

          livenessProbe:
            exec:
              command: ["sh","-c","pg_isready -U $POSTGRES_USER"]
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 6

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              memory: "1Gi"

      volumes:
        - name: postgres-config
          configMap:
            name:  postgres-init-scripts
            items:
              - key: postgresql.conf
                path: postgresql.conf

  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

